export const allSurveryFormsTemplate = [
  {
    id: "01",
    name: "zed",
    createdAt: "12/12/24",
    formElements: [],
  },
];

export const generateID = () => {
  return (
    Math.random().toString(36).substring(2, 15) +
    Math.random().toString(36).substring(2, 15)
  );
};

export const addNewSurvey = (id: string, name: string) => {
  allSurveryFormsTemplate.push({
    id: id,
    name: name,
    createdAt: "",
    formElements: [],
  });
};

export const FormItemTypes = {
  CONTROL: "control",
  CONTAINER: "container",
};

export const FormControlNames = {
  STEPCONTAINER: "step-container",
  INPUTTEXTFIELD: "text-field",
  INPUTMULTILINE: "multiline-text-field",
  CHECKBOX: "checkbox",
  RADIOGROUP: "radio-group",
  SELECTDROPDOWN: "select-drop-down",
  DATEFIELD: "date-field",
  TIMEFIELD: "time-field",
  FILEUPLOAD: "file-upload",
  IMAGEUPLOAD: "image-upload",
  TOGGLE: "toggle",
  CHECKLIST: "checklist",
  SIGNATURE: "signature",
  MULTICHOICES: "multi-choices",
  SCANCODE: "scan-code",
  VERIFIEDID: "verified-id",
};

export const FormTextDataTypes = {
  TEXT: "text",
};

export const FormContainerList = [
  {
    id: "",
    controlName: FormControlNames.STEPCONTAINER,
    displayText: "Workflow Step",
    itemType: FormItemTypes.CONTAINER,
    icon: "fa fa-building",
    heading: "Container Heading",
    subHeading: "Container SubHeading",
  },
];

export const FormControlList = [
  {
    id: "",
    controlName: FormControlNames.INPUTTEXTFIELD,
    displayText: "Text",
    placeholder: "Placeholder for Text Field",
    description: "Some Description about the field",
    labelName: "Text Field",
    itemType: FormItemTypes.CONTROL,
    dataType: FormTextDataTypes.TEXT,
    icon: "📝",
    required: false,
    category: "text-elements",
    containerId: "",
    element: "Short Answer",
  },
  {
    id: "",
    controlName: FormControlNames.INPUTMULTILINE,
    displayText: "Notes",
    description: "Some Description about the field",
    placeholder: "Please write your notes here.",
    labelName: "Notes",
    rows: 4,
    itemType: FormItemTypes.CONTROL,
    icon: "📖",
    required: false,
    category: "text-elements",
    containerId: "",
    element: "Open Ended",
  },
  {
    id: "",
    controlName: FormControlNames.RADIOGROUP,
    displayText: "Radio",
    description: "Some Description about the field",
    labelName: "Label for Radio",
    itemType: FormItemTypes.CONTROL,
    icon: "🔘",
    required: false,
    items: [
      {
        id: generateID(),
        value: "Button__-1",
        label: "Button 1",
      },
      {
        id: generateID(),
        value: "Button__-2",
        label: "Button 2",
      },
    ],
    category: "other-elements",
    containerId: "",
    element: "Radio",
  },
  // {
  //   id: "",
  //   controlName: FormControlNames.TOGGLE,
  //   displayText: "Toggle",
  //   description: "Some Description about the field",
  //   labelName: "Label for Toggle",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "fas fa-toggle-on",
  //   required: false,
  //   category: "other-elements",
  //   containerId: "",
  // },
  {
    id: "",
    controlName: FormControlNames.CHECKLIST,
    displayText: "Checklist",
    description: "Some Description about the field",
    labelName: "Label for Checklist",
    itemType: FormItemTypes.CONTROL,
    icon: "✅",
    required: false,
    items: [
      {
        id: generateID(),
        value: "Check__-1",
        label: "Check 1",
      },
      {
        id: generateID(),
        value: "Check__-2",
        label: "Check 2",
      },
    ],
    category: "other-elements",
    containerId: "",
    element: "Multiple Choice",
  },
  {
    id: "",
    controlName: FormControlNames.SELECTDROPDOWN,
    displayText: "Dropdown",
    description: "Some Description about the field",
    labelName: "Label for Dropdown",
    itemType: FormItemTypes.CONTROL,
    icon: "⬇️",
    required: false,
    items: [
      {
        id: generateID(),
        value: "Option__-1",
        label: "Option 1",
      },
      {
        id: generateID(),
        value: "Option__-2",
        label: "Option 2",
      },
    ],
    category: "other-elements",
    containerId: "",
    element: "Dropdown",
  },
  {
    id: "",
    controlName: FormControlNames.CHECKBOX,
    displayText: "Checkbox",
    description: "Some Description about the field",
    labelName: "Label for Checkbox",
    placeholder: "Place Holder Text",
    itemType: FormItemTypes.CONTROL,
    icon: "✔️",
    required: false,
    category: "other-elements",
    containerId: "",
    element: "Checkbox",
  },
  {
    id: "",
    controlName: FormControlNames.DATEFIELD,
    displayText: "Date",
    description: "Some Description about the field",
    labelName: "Label for Date",
    itemType: FormItemTypes.CONTROL,
    icon: "📅",
    required: false,
    category: "date-elements",
    containerId: "",
    element: "Date",
  },
  {
    id: "",
    controlName: FormControlNames.TIMEFIELD,
    displayText: "Time",
    description: "Some Description about the field",
    labelName: "Label for Time",
    itemType: FormItemTypes.CONTROL,
    icon: "⌚",
    required: false,
    category: "date-elements",
    containerId: "",
    element: "Time",
  },
  // {
  //   id: "",
  //   controlName: FormControlNames.SIGNATURE,
  //   displayText: "Signature",
  //   description: "Some Description about the field",
  //   labelName: "Label for Signature",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "fa fa-signature",
  //   required: false,
  //   category: "other-elements",
  //   containerId: "",
  // },
  // {
  //   id: "",
  //   controlName: FormControlNames.FILEUPLOAD,
  //   displayText: "Upload",
  //   description: "Some Description about the field",
  //   labelName: "Label for File Upload",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "fas fa-cloud-upload-alt",
  //   required: false,
  //   category: "media-elements",
  //   containerId: "",
  // },
  // {
  //   id: "",
  //   controlName: FormControlNames.IMAGEUPLOAD,
  //   displayText: "Image",
  //   description: "Some Description about the field",
  //   labelName: "Label for Image Upload",
  //   itemType: FormItemTypes.CONTROL,
  //   icon: "far fa-image",
  //   required: false,
  //   category: "media-elements",
  //   containerId: "",
  // },
  {
    id: generateID(),
    controlName: FormControlNames.STEPCONTAINER,
    displayText: "Workflow Step",
    itemType: FormItemTypes.CONTAINER,
    icon: "➕",
    heading: "Section Title",
    subHeading: "Description (If any)",
    element: "New Step",
  },
];
